### ISSUE TITLE
Support callback for header manipulation

### ISSUE THREAD

**Issue by trieloff** [Schibsted-Tech-Polska/nodesi#26]
See https://github.com/adobe/helix-experimental-dispatch/issues/6#issuecomment-516751125

We have a use case where we need to make sure that certain header values from the fragment are passed through to the consolidated response. In fact, we need to manipulate the header values, so that no duplicates exist.

For this, I would like to propose an additional property in `options`: `processHeaders: function(accumulator, currentValue)`, which takes a reducer function (using the same signature as `Array.prototype.reduce()` that will be called with the headers object of each fragment response and return the final value of `accumulator`. The initial value of the `accumulator` will be the object provided in the option `initialHeaders`.

This option then also serves as an output parameter, which can be accessed by users of `esi.process` without changing the signature.

**Comment by filipgolonka** [comment]
Sounds good!

**Comment by trieloff** [comment]
Glad to hear that

**Comment by bukowskiadam** [comment]
I'm not sure what to think about this issue 😄 I think it's not relevant anymore, because no one took care of it. I think that @filipgolonka agreed with the idea, but he didn't want to implement it (rather wait for a PR). And @trieloff didn't provide the PR, because probably thinking that maintainers will do that 🤷🏻‍♂️ So let's just close it.

**Comment by trieloff** [comment]
Yep, we stopped using ESI alltogether, so this made this use case in nodesi obsolete.
